version: "3"

services:
    nginx:
        build:
            context: docker/nginx
        volumes:
            - ./public:/var/www/symfony/public/:cached
        ports:
            - 8080:80
        depends_on:
            - php

    php:
        build:
            context: docker/php
        environment:
            APP_ENV: dev
        volumes:
            - .:/var/www/symfony/:cached
            - /var/www/symfony/vendor

    adminer:
        image: adminer:latest
        ports:
            - 8081:8080
