controllers:
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: '/api/v1'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
